import { useState, useEffect } from 'react';
import { sql } from '../db';
import { ArrowLeft, Brain, Zap, Trash2, Calendar } from 'lucide-react';

function HistoryView({ onBack }) {
    const [history, setHistory] = useState([]);
    const [loading, setLoading] = useState(true);

    const [expandedIds, setExpandedIds] = useState({});

    useEffect(() => {
        fetchHistory();
    }, []);

    const fetchHistory = async () => {
        setLoading(true);
        try {
            const data = await sql`SELECT * FROM storm_sessions ORDER BY created_at DESC LIMIT 50`;
            setHistory(data || []);
        } catch (error) {
            console.error('Error fetching history:', error.message);
        } finally {
            setLoading(false);
        }
    };

    const handleDelete = async (id, e) => {
        e.stopPropagation();
        if (!window.confirm('Are you sure you want to delete this session?')) return;

        try {
            await sql`DELETE FROM storm_sessions WHERE id = ${id}`;
            setHistory(prev => prev.filter(item => item.id !== id));
        } catch (error) {
            console.error('Error deleting session:', error.message);
            alert('Failed to delete session');
        }
    };

    const toggleExpand = (id) => {
        setExpandedIds(prev => ({
            ...prev,
            [id]: !prev[id]
        }));
    };

    const handleEmailHistory = (item, e) => {
        e.stopPropagation();
        const qs = Array.isArray(item.questions) ? item.questions : (typeof item.questions === 'string' ? JSON.parse(item.questions) : []);
        let subject = `Question Storm History: ${item.scenario}`;
        let report = `QUESTION STORMING HISTORY REPORT\n==========================\n`;
        report += `Challenge: ${item.scenario}\n`;
        report += `Date: ${new Date(item.created_at).toLocaleString()}\n`;
        report += `Mode: ${item.is_paradox ? 'PARADOX (13-Dice)' : 'Standard'}\n`;
        report += `Total Questions: ${qs.length}\n\n`;

        report += `QUESTIONS:\n`;
        qs.forEach((q, i) => {
            const qText = typeof q === 'string' ? q : q.text;
            const constraint = q.paradoxConstraint ? ` (Anomaly: ${q.paradoxConstraint})` : '';
            report += `[${i + 1}] ${qText}${constraint}\n`;
        });

        report += `\n_Generated by Question Storming App_`;

        const mailtoUrl = `mailto:?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(report)}`;
        window.location.href = mailtoUrl;
    };

    const handleEmailAllHistory = () => {
        if (history.length === 0) return;

        let subject = `Question Storming: Full Session History`;
        let report = `QUESTION STORMING - FULL SESSION HISTORY\n`;
        report += `=========================================\n\n`;

        history.forEach((item, index) => {
            const qs = Array.isArray(item.questions) ? item.questions : (typeof item.questions === 'string' ? JSON.parse(item.questions) : []);
            report += `SESSION #${index + 1}\n`;
            report += `Challenge: ${item.scenario}\n`;
            report += `Date: ${new Date(item.created_at).toLocaleString()}\n`;
            report += `Questions: ${qs.length}\n`;
            report += `-----------------------------------------\n`;
            qs.forEach((q, i) => {
                const qText = typeof q === 'string' ? q : q.text;
                report += `  [${i + 1}] ${qText}\n`;
            });
            report += `\n\n`;
        });

        report += `_Generated by Question Storming App_`;

        const mailtoUrl = `mailto:?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(report)}`;
        window.location.href = mailtoUrl;
    };

    const formatDate = (dateString) => {
        return new Date(dateString).toLocaleDateString(undefined, {
            month: 'short',
            day: 'numeric',
            year: 'numeric',
            hour: '2-digit',
            minute: '2-digit'
        });
    };

    return (
        <div className="history-container fade-in">
            <div className="history-header">
                <button onClick={onBack} className="back-btn">
                    <ArrowLeft size={20} />
                    Back
                </button>
                <h2>Storm History</h2>
                {history.length > 0 && (
                    <button onClick={handleEmailAllHistory} className="icon-btn" title="Email Full History" style={{ width: 'auto', padding: '0 1rem', display: 'flex', gap: '0.4rem', fontSize: '0.85rem' }}>
                        <Mail size={16} /> Email All
                    </button>
                )}
            </div>

            {loading ? (
                <div className="loading-state">Loading your past storms...</div>
            ) : history.length === 0 ? (
                <div className="empty-state">
                    <Brain size={48} className="muted-icon" />
                    <p>No brainstorms saved yet. Start your first session!</p>
                </div>
            ) : (
                <div className="history-list">
                    {history.map((item) => (
                        <div
                            key={item.id}
                            className={`history-card ${item.is_paradox ? 'paradox-history' : ''} ${expandedIds[item.id] ? 'expanded' : ''}`}
                            onClick={() => toggleExpand(item.id)}
                            style={{ cursor: 'pointer' }}
                        >
                            <div className="history-card-header">
                                <div className="history-meta">
                                    <span className="history-date">
                                        <Calendar size={14} />
                                        {formatDate(item.created_at)}
                                    </span>
                                    {item.is_paradox && (
                                        <span className="history-badge paradox">
                                            <Zap size={12} /> 13-Dice
                                        </span>
                                    )}
                                </div>
                                <div className="history-actions">
                                    <span className="history-count">
                                        {item.questions?.length || 0} Questions
                                    </span>
                                    <button
                                        className="icon-btn"
                                        onClick={(e) => handleEmailHistory(item, e)}
                                        title="Email this session"
                                        style={{ width: '32px', height: '32px', border: 'none', background: 'transparent' }}
                                    >
                                        <Mail size={16} />
                                    </button>
                                    <button
                                        className="history-delete-btn"
                                        onClick={(e) => handleDelete(item.id, e)}
                                        title="Delete Session"
                                    >
                                        <Trash2 size={16} />
                                    </button>
                                </div>
                            </div>
                            <h3 className="history-scenario">{item.scenario}</h3>
                            <div className="history-preview">
                                {(expandedIds[item.id] ? item.questions : item.questions?.slice(0, 2))?.map((q, i) => (
                                    <p key={i} className="preview-item">
                                        <span className="q-num">{String(i + 1).padStart(2, '0')}.</span> {q.text}
                                    </p>
                                ))}
                                {!expandedIds[item.id] && item.questions?.length > 2 && (
                                    <p className="more-indicator">... click to view {item.questions.length - 2} more</p>
                                )}
                            </div>
                        </div>
                    ))}
                </div>
            )}
        </div>
    );
}

export default HistoryView;
