import { ArrowLeft, Clock, BarChart3, ListChecks, Zap, Download, FileText, Brain, Mail } from 'lucide-react';

function SessionAnalysis({ session, onBack }) {
    const { scenario, questions, isParadoxMode, duration, created_at } = session;
    const starredQuestions = questions.filter(q => q.starred);
    const totalQuestions = questions.length;

    // Calculate metrics
    const minutes = duration / 60;
    const questionsPerMinute = (totalQuestions / (minutes || 1)).toFixed(1);

    const formatDate = (dateString) => {
        if (!dateString) return new Date().toLocaleDateString();
        return new Date(dateString).toLocaleDateString(undefined, {
            weekday: 'long',
            year: 'numeric',
            month: 'long',
            day: 'numeric',
            hour: '2-digit',
            minute: '2-digit'
        });
    };

    const handleEmailReport = () => {
        const reportContent = `
QUESTION STORMING ANALYSIS REPORT
==================================
Date: ${formatDate(created_at)}
Challenge: ${scenario}
Mode: ${isParadoxMode ? 'PARADOX (Singularity)' : 'Standard'}
Duration: ${duration} seconds

STATISTICAL AUDIT
-----------------
Total Questions Generated: ${totalQuestions}
Storm Density: ${questionsPerMinute} questions/min

TOP OUTCOMES (Starred)
----------------------
${starredQuestions.length > 0
                ? starredQuestions.map((q, i) => `${i + 1}. ${q.text}`).join('\n')
                : 'No questions were starred.'}

FULL AUDIT TRAIL
----------------
${questions.map((q, i) => `[${i + 1}] ${q.text}${q.paradoxConstraint ? `\n    Reality Interference: ${q.paradoxConstraint}` : ''}`).join('\n')}

----------------------------------
Generated by Question Storming Engine
"Roll the dice for a 13" methodology by Fail On Purpose (www.failonpurpose.com)
        `.trim();

        const subject = `Question Storming Audit: ${scenario}`;
        const mailtoUrl = `mailto:?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(reportContent)}`;
        window.location.href = mailtoUrl;
    };

    const handleDownloadReport = () => {
        const reportContent = `
QUESTION STORMING ANALYSIS REPORT
==================================
Date: ${formatDate(created_at)}
Challenge: ${scenario}
Mode: ${isParadoxMode ? 'PARADOX (Singularity)' : 'Standard'}
Duration: ${duration} seconds

STATISTICAL AUDIT
-----------------
Total Questions Generated: ${totalQuestions}
Storm Density: ${questionsPerMinute} questions/min

TOP OUTCOMES (Starred)
----------------------
${starredQuestions.length > 0
                ? starredQuestions.map((q, i) => `${i + 1}. ${q.text}`).join('\n')
                : 'No questions were starred.'}

FULL AUDIT TRAIL
----------------
${questions.map((q, i) => `[${i + 1}] ${q.text}${q.paradoxConstraint ? `\n    Reality Interference: ${q.paradoxConstraint}` : ''}`).join('\n')}

----------------------------------
Generated by Question Storming Engine
"Roll the dice for a 13" methodology by Fail On Purpose (www.failonpurpose.com)
        `.trim();

        const blob = new Blob([reportContent], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        link.download = `storm_report_${new Date().getTime()}.txt`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        URL.revokeObjectURL(url);
    };

    return (
        <div className="analysis-container fade-in">
            <div className="analysis-header-row">
                <button onClick={onBack} className="back-btn">
                    <ArrowLeft size={18} />
                    Back to Review
                </button>
                <div className="analysis-actions" style={{ display: 'flex', gap: '0.5rem' }}>
                    <button onClick={handleEmailReport} className="primary-btn report-btn" style={{ background: 'var(--surface-color)', border: '1px solid var(--border-color)', color: 'var(--text-color)' }}>
                        <Mail size={18} />
                        Email Report
                    </button>
                    <button onClick={handleDownloadReport} className="primary-btn report-btn">
                        <FileText size={18} />
                        Export Audit Report
                    </button>
                </div>
            </div>

            <div className="report-card">
                <div className="report-badge">SESSION AUDIT TRAIL</div>
                <h2 className="report-title">{scenario}</h2>
                <div className="report-meta">
                    <div className="meta-item">
                        <Clock size={16} />
                        <span>{formatDate(created_at)}</span>
                    </div>
                    <div className="meta-item">
                        {isParadoxMode ? <Zap size={16} className="active-icon" /> : <BarChart3 size={16} />}
                        <span>{isParadoxMode ? 'Roll the dice for a 13' : 'Standard Session'}</span>
                    </div>
                </div>

                <div className="metrics-grid">
                    <div className="metric-box">
                        <span className="metric-value">{totalQuestions}</span>
                        <span className="metric-label">Total Questions</span>
                    </div>
                    <div className="metric-box">
                        <span className="metric-value">{questionsPerMinute}</span>
                        <span className="metric-label">Questions / Min</span>
                    </div>
                    <div className="metric-box">
                        <span className="metric-value">{starredQuestions.length}</span>
                        <span className="metric-label">Key Outcomes</span>
                    </div>
                </div>

                <div className="report-section insight-section">
                    <h3><Brain size={18} /> Insight Analysis</h3>
                    <div className="insight-content">
                        <p>
                            {questionsPerMinute > 5
                                ? `A high-intensity session with a storm density of ${questionsPerMinute} questions per minute. This suggests a fluent rapid-fire ideation state, often associated with breaking through superficial assumptions.`
                                : questionsPerMinute > 2
                                    ? `A steady and deliberate session. A density of ${questionsPerMinute} questions per minute indicates a balanced pace of reflection and generation.`
                                    : `A deep-dive session. The lower frequency suggests each question was carefully considered, potentially leading to more complex organizational inquiries.`}
                        </p>
                        <p style={{ marginTop: '0.5rem' }}>
                            {starredQuestions.length > 0
                                ? `Out of ${totalQuestions} questions, ${starredQuestions.length} were identified as critical pivots (${((starredQuestions.length / totalQuestions) * 100).toFixed(0)}% focus rate). These "Key Outcomes" represent the most likely candidates for actionable strategy.`
                                : `The session prioritized exploration over selection. While no questions were starred, the total volume of ${totalQuestions} provides a wide base for future categorization.`}
                        </p>
                    </div>
                </div>


                <div className="report-section">
                    <h3><Star size={18} style={{ color: 'var(--accent-color)' }} /> Key Outcomes</h3>
                    <div className="analysis-starred-list">
                        {starredQuestions.length > 0 ? (
                            starredQuestions.map((q, i) => (
                                <div key={q.id} className="analysis-card starred">
                                    <div className="analysis-num">0{i + 1}</div>
                                    <div className="analysis-text">{q.text}</div>
                                </div>
                            ))
                        ) : (
                            <p className="muted-text">No questions were starred as key outcomes.</p>
                        )}
                    </div>
                </div>

                <div className="report-section">
                    <h3><ListChecks size={18} /> Complete Audit Trail</h3>
                    <div className="audit-trail-list">
                        {questions.map((q, i) => (
                            <div key={q.id} className="audit-item">
                                <span className="audit-index">{String(i + 1).padStart(2, '0')}</span>
                                <div className="audit-content">
                                    <span className="audit-text">{q.text}</span>
                                    {q.paradoxConstraint && (
                                        <div className="audit-constraint">
                                            <Zap size={10} />
                                            Active Constraint: {q.paradoxConstraint}
                                        </div>
                                    )}
                                </div>
                                {q.starred && <span className="audit-star-tag">STARRED</span>}
                            </div>
                        ))}
                    </div>
                </div>
            </div>
        </div>
    );
}

// Minimal Star icon since lucide-react is imported in components
const Star = ({ size, style }) => (
    <svg width={size} height={size} viewBox="0 0 24 24" fill="currentColor" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" style={style}>
        <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"></polygon>
    </svg>
);

export default SessionAnalysis;
